# Generated by Django 5.1.2 on 2024-10-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projile',
            new_name='Profile',
        ),
    ]
